### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'data/20newsgroups/20_simplified/train_1024.tsv'

### ISSUE THREAD

**Issue by oosij** [franborjavalero/RoBERT-text-classification#2]
lib/python3.6/site-packages/nltk/data.py", line 583, in find
    raise LookupError(resource_not_found)
LookupError:

....
 File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'data/20newsgroups/20_simplified/train_1024.tsv'

I ran this program, but it didn't work properly. Has anyone run it?

**Comment by franbvalero** [comment]
Hi @oosij, I'm so sorry for replying 3 months later, but last time I was not very active on GitHub.

I guess you got this error when you launched `launch-hierarchical-experiments-20newsgroups.sh`.

If you review the script and the two code blocks shown in the **Usage** section of the [**README**](https://github.com/franbvalero/BERT-long-sentence-classification#usage), you will find that you have to give an argument to download and process the corpus of 20 newsgroups. This argument could be `True` or any string:

`./launch-hierarchical-experiments-20newsgroups.sh True`

Let me know if this solves your problem.
